### ISSUE TITLE
Add support for 'bind-key S-Left' and 'bind-key S-Right'

### ISSUE THREAD

**Issue by cschar** [prompt-toolkit/pymux#53]
The following works in my local tmux.conf but I think it isn't supported in pymux (or in prompt_toolkit?)

```
# Shift arrow to switch windows
bind-key -n S-Left  previous-window
bind-key -n S-Right next-window
```

**Comment by jonathanslenders** [comment]
Thank you @cclay for this feature request.
It was not yet supported in prompt_toolkit. Now it is: https://github.com/jonathanslenders/python-prompt-toolkit/commit/6c76f472c76c35c70ea03f6fe6328d41b6fc6c3d

This pull request should do expose this functionality in Pymux: https://github.com/jonathanslenders/pymux/pull/54
I'll merge it after the next prompt_toolkit release.

**Comment by tamwile** [comment]
I think we can close this one ?
